"""`pip_parse` module extension — uv.lock → @<hub> + per-pkg repos.

Counterpart to rules_python's `pip_parse`, but driven by uv.lock
instead of requirements.txt. For each package the lockfile resolves
to, we create a Bazel-fetched repo containing the unpacked wheel
(or sdist, as a v0.1 fallback). A hub repo aggregates these and
exposes a `requirement("<name>")` macro plus pre-aliased
`@<hub>//<name>:pkg` labels.

Consumer:

    pip = use_extension("@rules_uv//pip:extensions.bzl", "pip")
    pip.parse(
        hub_name = "pip",
        lock = "//:uv.lock",
    )
    use_repo(pip, "pip")

Then in BUILD files:

    load("@pip//:requirements.bzl", "requirement")

    py_library(
        name = "app",
        srcs = ["app.py"],
        deps = [requirement("requests")],
    )

Limitations (deferred to v0.2):

  * Native-wheel selection: only pure-python wheels + sdist fallback
    are wired today (see `wheel_selection.bzl`).
  * Optional-dependency groups + extras: dropped on the floor by the
    JSON projection (see `uvlock_to_json.py`).
  * Editable + git + path sources: tolerated in the lockfile (we
    record them as `source = "..."` strings) but produce no
    materialized repo. They are intended for v0.2 (`uv pip install
    --target` for sdists; thin BUILD wrappers for path entries).
"""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
load("//pip/private:wheel_selection.bzl", "select_artifact")

# -----------------------------------------------------------------------------
# Per-package repo rule. Materializes the wheel (or sdist) under
# @<hub>__<normalized_pkg>.
# -----------------------------------------------------------------------------

def _make_pkg_repo(hub_name, pkg, build_tpl):
    artifact = select_artifact(pkg)
    repo_name = _pkg_repo_name(hub_name, pkg["name"])

    deps_labels = [
        "@{}__{}//:pkg".format(hub_name, _normalize(d))
        for d in pkg.get("dependencies", [])
    ]
    deps_str = ", ".join(['"{}"'.format(d) for d in deps_labels])
    build_file_content = build_tpl \
        .replace("{NAME}", pkg["name"]) \
        .replace("{VERSION}", pkg.get("version", "")) \
        .replace("{DEPS}", deps_str)

    if artifact.kind == "wheel":
        # http_archive unpacks .whl files transparently (Bazel treats
        # them as zip). The resulting tree is the importable package.
        http_archive(
            name = repo_name,
            url = artifact.url,
            sha256 = artifact.sha256,
            type = "zip",
            build_file_content = build_file_content,
        )
    else:
        # sdist path: keep the tarball as a data file. v0.1 doesn't
        # actually install it; the py_library above globs anything
        # that happens to live alongside. Real sdist support is a
        # v0.2 deliverable.
        http_file(
            name = repo_name,
            url = artifact.url,
            sha256 = artifact.sha256,
            downloaded_file_path = artifact.filename,
        )

# -----------------------------------------------------------------------------
# Hub repo — emits `requirements.bzl` with the `requirement()` macro.
# -----------------------------------------------------------------------------

def _hub_repo_impl(repository_ctx):
    package_names = repository_ctx.attr.package_names
    hub_name = repository_ctx.attr.hub_name

    # Per-package repos live in the same module-extension namespace
    # as the hub, so the hub can reference them, but the consuming
    # workspace cannot. We re-expose each as an `alias` under
    # `@<hub>//<name>:pkg` so consumer BUILD files only ever see the
    # hub repo name (which they import via `use_repo`).
    alias_entries = []
    requirement_entries = []
    for name in package_names:
        norm = _normalize(name)
        alias_entries.append(
            'alias(name = "{n}", actual = "@{hub}__{n}//:pkg")'.format(
                n = norm,
                hub = hub_name,
            ),
        )
        requirement_entries.append(
            '    "{}": Label("@{}//:{}"),'.format(norm, hub_name, norm),
        )

    repository_ctx.file("BUILD.bazel", """\
package(default_visibility = ["//visibility:public"])
exports_files(["requirements.bzl"])

{aliases}
""".format(aliases = "\n".join(alias_entries)))

    repository_ctx.file("requirements.bzl", """\
\"\"\"Generated by rules_uv//pip:extensions.bzl. Do not edit.\"\"\"

_REQUIREMENTS = {{
{entries}
}}

def requirement(name):
    \"\"\"Resolve a package name to its Bazel label.\"\"\"
    norm = name.lower().replace("_", "-").replace(".", "-")
    if norm not in _REQUIREMENTS:
        fail("rules_uv/pip: unknown package {{!r}} (known: {{}})".format(
            name, sorted(_REQUIREMENTS.keys()),
        ))
    return _REQUIREMENTS[norm]

ALL_REQUIREMENTS = [v for _, v in sorted(_REQUIREMENTS.items())]
""".format(entries = "\n".join(requirement_entries)))

_hub_repo = repository_rule(
    implementation = _hub_repo_impl,
    attrs = {
        "hub_name": attr.string(mandatory = True),
        "package_names": attr.string_list(mandatory = True),
    },
)

# -----------------------------------------------------------------------------
# Top-level: read uv.lock via tomllib (python3.11 helper) and fan out.
# -----------------------------------------------------------------------------

def _read_lock(mctx, lock_label):
    lock_path = mctx.path(lock_label)
    script = mctx.path(Label("//pip/private:uvlock_to_json.py"))
    python = mctx.which("python3") or mctx.which("python")
    if not python:
        fail("rules_uv/pip: no python3 on PATH — needed to parse uv.lock " +
             "(uses Python's stdlib tomllib).")
    result = mctx.execute([python, script, lock_path], quiet = True)
    if result.return_code != 0:
        fail("rules_uv/pip: uvlock_to_json failed: " + result.stderr)
    return json.decode(result.stdout)

def _pip_extension_impl(mctx):
    build_tpl_path = mctx.path(
        Label("//pip/private:pip_package.BUILD.tpl"),
    )
    build_tpl = mctx.read(build_tpl_path)

    for mod in mctx.modules:
        for tag in mod.tags.parse:
            lock = _read_lock(mctx, tag.lock)
            pkg_names = []
            for pkg in lock["packages"]:
                if pkg["source"] not in ("registry", "url"):
                    # Skip git/path/editable/virtual — see module
                    # docstring. The hub still records the name so
                    # consumer code that references it gets a clearer
                    # error than "undefined label".
                    continue
                _make_pkg_repo(tag.hub_name, pkg, build_tpl)
                pkg_names.append(pkg["name"])
            _hub_repo(
                name = tag.hub_name,
                hub_name = tag.hub_name,
                package_names = pkg_names,
            )

_parse_tag = tag_class(attrs = {
    "hub_name": attr.string(
        default = "pip",
        doc = "Name of the hub repo (the @<hub_name>//... namespace).",
    ),
    "lock": attr.label(
        mandatory = True,
        allow_single_file = True,
        doc = "Label pointing at a uv.lock file.",
    ),
})

pip = module_extension(
    implementation = _pip_extension_impl,
    tag_classes = {"parse": _parse_tag},
    doc = "Materialize @<hub> + per-pkg repos from a uv.lock.",
)

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------

def _normalize(name):
    # PEP 503 canonical name: lowercase, _/. → -.
    return name.lower().replace("_", "-").replace(".", "-")

def _pkg_repo_name(hub_name, pkg_name):
    return "{}__{}".format(hub_name, _normalize(pkg_name))
