# Generated by rules_uv//pip:extensions.bzl for the {NAME} package
# (version {VERSION}). Do not edit by hand — re-run `bazel build`
# after editing the lockfile to regenerate.

load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "whl",
    srcs = glob(["**/*.whl", "**/*.tar.gz"], allow_empty = True),
)

# For wheels, the unpacked contents already form an importable
# package tree at the repo root; for sdists, this is a "we have the
# tarball, downstream needs to install it" stub. v0.2 will wire
# sdists through `uv pip install --target` to produce a proper
# py_library tree.
py_library(
    name = "pkg",
    srcs = glob(
        ["**/*.py"],
        allow_empty = True,
    ),
    data = glob(
        ["**/*"],
        exclude = [
            "**/*.py",
            "**/__pycache__/**",
            "**/*.dist-info/RECORD",
            "BUILD.bazel",
            "WORKSPACE",
        ],
        allow_empty = True,
    ),
    imports = ["."],
    deps = [{DEPS}],
)
