"""repository_rule that downloads + installs a Python sdist via uv.

`uv pip install --target=. --no-deps <sdist>` lets uv handle the
build (PEP 517 backend invocation, native compile if needed, wheel
unpack) and lands the result as an importable tree at the repo
root. From Bazel's perspective the repo is then just a `py_library`
globbing `**/*.py`.

The rule chooses a Python interpreter based on the `python_strategy`
attr:

  * `"host"`     — Resolve via `repository_ctx.which("python3")`.
                   Fast; trusts the user's host Python is ≥ the
                   `python_version` they configured.

  * `"uv"`       — Run `<uv> python install <version>` into a
                   per-repo scratch dir and use the resulting
                   interpreter. Hermetic; one-time download per
                   fresh Bazel cache (uv handles caching).

The `--python` flag is only added when an explicit interpreter is
known; otherwise we let uv pick (it has its own discovery order:
`VIRTUAL_ENV`, `UV_PYTHON`, `python3` on PATH, then its own managed
versions).
"""

# BUILD content emitted for the resulting install tree. Mirrors
# pip_package.BUILD.tpl's shape so wheel + sdist consumers share the
# same py_library import surface.
_SDIST_BUILD_TPL = """\
# Generated by rules_uv//pip:sdist_install.bzl for {NAME} ({VERSION}).
# `uv pip install --target=.` materialized this tree from the sdist.

load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "pkg",
    srcs = glob(
        ["**/*.py"],
        allow_empty = True,
    ),
    data = glob(
        ["**/*"],
        exclude = [
            "**/*.py",
            "**/__pycache__/**",
            "**/*.dist-info/RECORD",
            "BUILD.bazel",
            "WORKSPACE",
        ],
        allow_empty = True,
    ),
    imports = ["."],
    deps = [{DEPS}],
)
"""

def _resolve_python(rctx):
    """Return a path to a Python interpreter, per the configured strategy."""
    if rctx.attr.python_strategy == "host":
        python = rctx.which("python3") or rctx.which("python")
        if not python:
            fail(
                "rules_uv/pip: python_strategy = \"host\" but no python3 " +
                "on PATH for {}. Either install python3 or switch to " +
                "python_strategy = \"uv\".".format(rctx.attr.pkg_name),
            )
        return str(python)

    # python_strategy = "uv": ask uv to manage an interpreter.
    uv = str(rctx.path(rctx.attr.uv))
    install_dir = rctx.path("python")
    args = [
        uv,
        "python",
        "install",
        rctx.attr.python_version,
        "--install-dir",
        str(install_dir),
    ]
    result = rctx.execute(args)
    if result.return_code != 0:
        fail(
            "rules_uv/pip: `uv python install {ver}` failed for {pkg}:\n{out}\n{err}".format(
                ver = rctx.attr.python_version,
                pkg = rctx.attr.pkg_name,
                out = result.stdout,
                err = result.stderr,
            ),
        )
    # uv's install dir gets a sub-tree like
    # `cpython-<ver>-<triple>/bin/python3`. Find the first python3
    # binary by walking the install dir. `rctx.path().readdir()` is
    # bzlmod-only but stable.
    for child in install_dir.readdir():
        candidate = child.get_child("bin").get_child("python3")
        if candidate.exists:
            return str(candidate)
    fail(
        "rules_uv/pip: uv python install for {} produced no bin/python3 in {}".format(
            rctx.attr.pkg_name,
            install_dir,
        ),
    )

def _sdist_install_impl(rctx):
    # Step 1: download the sdist.
    sdist_filename = rctx.attr.url.rsplit("/", 1)[-1]
    rctx.download(
        url = rctx.attr.url,
        sha256 = rctx.attr.sha256,
        output = sdist_filename,
    )

    # Step 2: pick a Python interpreter.
    python_bin = _resolve_python(rctx)

    # Step 3: shell to uv to install into the repo root. `--no-deps`
    # is critical — each package gets installed in isolation, and
    # the dependency graph is reconstructed at Bazel-graph level via
    # the per-pkg BUILD files.
    uv_bin = str(rctx.path(rctx.attr.uv))
    args = [
        uv_bin,
        "pip",
        "install",
        "--target=.",
        "--no-deps",
        "--python",
        python_bin,
        sdist_filename,
    ]
    result = rctx.execute(args, quiet = False)
    if result.return_code != 0:
        fail(
            "rules_uv/pip: `uv pip install {sd}` failed for {pkg}:\n{out}\n{err}".format(
                sd = sdist_filename,
                pkg = rctx.attr.pkg_name,
                out = result.stdout,
                err = result.stderr,
            ),
        )

    # Step 4: drop the BUILD file.
    deps_str = ", ".join(['"{}"'.format(d) for d in rctx.attr.deps])
    rctx.file(
        "BUILD.bazel",
        _SDIST_BUILD_TPL \
            .replace("{NAME}", rctx.attr.pkg_name) \
            .replace("{VERSION}", rctx.attr.pkg_version) \
            .replace("{DEPS}", deps_str),
    )

    # Step 5: clean up the downloaded sdist file so it doesn't show
    # up in glob() above. (The dist-info already lives in the unpacked
    # tree post-install.)
    rctx.delete(sdist_filename)

sdist_install_repo = repository_rule(
    implementation = _sdist_install_impl,
    attrs = {
        "url": attr.string(mandatory = True),
        "sha256": attr.string(mandatory = True),
        "pkg_name": attr.string(mandatory = True),
        "pkg_version": attr.string(default = ""),
        "deps": attr.string_list(default = []),
        "uv": attr.label(
            mandatory = True,
            executable = False,
            allow_single_file = True,
            doc = "Label of the uv binary (typically @uv//:binary).",
        ),
        "python_strategy": attr.string(
            default = "host",
            values = ["host", "uv"],
            doc = "Where to find a Python interpreter: `host` " +
                  "(`python3` on PATH) or `uv` (uv-managed install).",
        ),
        "python_version": attr.string(
            default = "3.12",
            doc = "Python version uv should install (only used when " +
                  "python_strategy = \"uv\").",
        ),
    },
    doc = "Install a Python sdist via `uv pip install --target=.`.",
)
